// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventTypeHasBookingsErrorCode.
const (
	EventTypeHasBookings EventTypeHasBookingsErrorCode = "event_type_has_bookings"
)

// Valid indicates whether the value is a known member of the EventTypeHasBookingsErrorCode enum.
func (e EventTypeHasBookingsErrorCode) Valid() bool {
	switch e {
	case EventTypeHasBookings:
		return true
	default:
		return false
	}
}

// Defines values for NotFoundErrorCode.
const (
	NotFound NotFoundErrorCode = "not_found"
)

// Valid indicates whether the value is a known member of the NotFoundErrorCode enum.
func (e NotFoundErrorCode) Valid() bool {
	switch e {
	case NotFound:
		return true
	default:
		return false
	}
}

// Defines values for SlotAlreadyBookedErrorCode.
const (
	SlotAlreadyBooked SlotAlreadyBookedErrorCode = "slot_already_booked"
)

// Valid indicates whether the value is a known member of the SlotAlreadyBookedErrorCode enum.
func (e SlotAlreadyBookedErrorCode) Valid() bool {
	switch e {
	case SlotAlreadyBooked:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorCode.
const (
	ValidationErrorCodeValidationError ValidationErrorCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ValidationErrorCode enum.
func (e ValidationErrorCode) Valid() bool {
	switch e {
	case ValidationErrorCodeValidationError:
		return true
	default:
		return false
	}
}

// Booking defines model for Booking.
type Booking = GuestInfo

// CreateBookingRequest defines model for CreateBookingRequest.
type CreateBookingRequest struct {
	EventTypeId string    `json:"eventTypeId"`
	GuestEmail  string    `json:"guestEmail"`
	GuestName   string    `json:"guestName"`
	GuestPhone  *string   `json:"guestPhone,omitempty"`
	Notes       *string   `json:"notes,omitempty"`
	StartTime   time.Time `json:"startTime"`
}

// CreateEventTypeRequest defines model for CreateEventTypeRequest.
type CreateEventTypeRequest struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// EventType defines model for EventType.
type EventType struct {
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
}

// EventTypeHasBookingsError defines model for EventTypeHasBookingsError.
type EventTypeHasBookingsError struct {
	Code    EventTypeHasBookingsErrorCode `json:"code"`
	Message string                        `json:"message"`
}

// EventTypeHasBookingsErrorCode defines model for EventTypeHasBookingsError.Code.
type EventTypeHasBookingsErrorCode string

// GuestInfo defines model for GuestInfo.
type GuestInfo struct {
	GuestEmail string  `json:"guestEmail"`
	GuestName  string  `json:"guestName"`
	GuestPhone *string `json:"guestPhone,omitempty"`
	Notes      *string `json:"notes,omitempty"`
}

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	Code    NotFoundErrorCode `json:"code"`
	Message string            `json:"message"`
}

// NotFoundErrorCode defines model for NotFoundError.Code.
type NotFoundErrorCode string

// Slot defines model for Slot.
type Slot struct {
	EndTime   time.Time `json:"endTime"`
	StartTime time.Time `json:"startTime"`
}

// SlotAlreadyBookedError defines model for SlotAlreadyBookedError.
type SlotAlreadyBookedError struct {
	Code                 SlotAlreadyBookedErrorCode `json:"code"`
	ConflictingBookingId string                     `json:"conflictingBookingId"`
	Message              string                     `json:"message"`
}

// SlotAlreadyBookedErrorCode defines model for SlotAlreadyBookedError.Code.
type SlotAlreadyBookedErrorCode string

// UpdateEventTypeRequest defines model for UpdateEventTypeRequest.
type UpdateEventTypeRequest struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Code    ValidationErrorCode `json:"code"`
	Message string              `json:"message"`
}

// ValidationErrorCode defines model for ValidationError.Code.
type ValidationErrorCode string

// AdminBookingsListAdminBookingsParams defines parameters for AdminBookingsListAdminBookings.
type AdminBookingsListAdminBookingsParams struct {
	From        *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To          *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
	EventTypeId *string             `form:"eventTypeId,omitempty" json:"eventTypeId,omitempty"`
}

// AdminEventTypesDeleteEventTypedefaultJSONResponseBody defines parameters for AdminEventTypesDeleteEventType.
type AdminEventTypesDeleteEventTypedefaultJSONResponseBody struct {
	union json.RawMessage
}

// BookingsCreateBookingdefaultJSONResponseBody defines parameters for BookingsCreateBooking.
type BookingsCreateBookingdefaultJSONResponseBody struct {
	union json.RawMessage
}

// SlotsListSlotsParams defines parameters for SlotsListSlots.
type SlotsListSlotsParams struct {
	EventTypeId string              `form:"eventTypeId" json:"eventTypeId"`
	From        *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To          *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// AdminEventTypesCreateEventTypeJSONRequestBody defines body for AdminEventTypesCreateEventType for application/json ContentType.
type AdminEventTypesCreateEventTypeJSONRequestBody = CreateEventTypeRequest

// AdminEventTypesUpdateEventTypeJSONRequestBody defines body for AdminEventTypesUpdateEventType for application/json ContentType.
type AdminEventTypesUpdateEventTypeJSONRequestBody = UpdateEventTypeRequest

// BookingsCreateBookingJSONRequestBody defines body for BookingsCreateBooking for application/json ContentType.
type BookingsCreateBookingJSONRequestBody = CreateBookingRequest

// AsNotFoundError returns the union data inside the AdminEventTypesDeleteEventTypedefaultJSONResponseBody as a NotFoundError
func (t AdminEventTypesDeleteEventTypedefaultJSONResponseBody) AsNotFoundError() (NotFoundError, error) {
	var body NotFoundError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNotFoundError overwrites any union data inside the AdminEventTypesDeleteEventTypedefaultJSONResponseBody as the provided NotFoundError
func (t *AdminEventTypesDeleteEventTypedefaultJSONResponseBody) FromNotFoundError(v NotFoundError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNotFoundError performs a merge with any union data inside the AdminEventTypesDeleteEventTypedefaultJSONResponseBody, using the provided NotFoundError
func (t *AdminEventTypesDeleteEventTypedefaultJSONResponseBody) MergeNotFoundError(v NotFoundError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEventTypeHasBookingsError returns the union data inside the AdminEventTypesDeleteEventTypedefaultJSONResponseBody as a EventTypeHasBookingsError
func (t AdminEventTypesDeleteEventTypedefaultJSONResponseBody) AsEventTypeHasBookingsError() (EventTypeHasBookingsError, error) {
	var body EventTypeHasBookingsError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEventTypeHasBookingsError overwrites any union data inside the AdminEventTypesDeleteEventTypedefaultJSONResponseBody as the provided EventTypeHasBookingsError
func (t *AdminEventTypesDeleteEventTypedefaultJSONResponseBody) FromEventTypeHasBookingsError(v EventTypeHasBookingsError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEventTypeHasBookingsError performs a merge with any union data inside the AdminEventTypesDeleteEventTypedefaultJSONResponseBody, using the provided EventTypeHasBookingsError
func (t *AdminEventTypesDeleteEventTypedefaultJSONResponseBody) MergeEventTypeHasBookingsError(v EventTypeHasBookingsError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AdminEventTypesDeleteEventTypedefaultJSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AdminEventTypesDeleteEventTypedefaultJSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSlotAlreadyBookedError returns the union data inside the BookingsCreateBookingdefaultJSONResponseBody as a SlotAlreadyBookedError
func (t BookingsCreateBookingdefaultJSONResponseBody) AsSlotAlreadyBookedError() (SlotAlreadyBookedError, error) {
	var body SlotAlreadyBookedError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSlotAlreadyBookedError overwrites any union data inside the BookingsCreateBookingdefaultJSONResponseBody as the provided SlotAlreadyBookedError
func (t *BookingsCreateBookingdefaultJSONResponseBody) FromSlotAlreadyBookedError(v SlotAlreadyBookedError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSlotAlreadyBookedError performs a merge with any union data inside the BookingsCreateBookingdefaultJSONResponseBody, using the provided SlotAlreadyBookedError
func (t *BookingsCreateBookingdefaultJSONResponseBody) MergeSlotAlreadyBookedError(v SlotAlreadyBookedError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationError returns the union data inside the BookingsCreateBookingdefaultJSONResponseBody as a ValidationError
func (t BookingsCreateBookingdefaultJSONResponseBody) AsValidationError() (ValidationError, error) {
	var body ValidationError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationError overwrites any union data inside the BookingsCreateBookingdefaultJSONResponseBody as the provided ValidationError
func (t *BookingsCreateBookingdefaultJSONResponseBody) FromValidationError(v ValidationError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationError performs a merge with any union data inside the BookingsCreateBookingdefaultJSONResponseBody, using the provided ValidationError
func (t *BookingsCreateBookingdefaultJSONResponseBody) MergeValidationError(v ValidationError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BookingsCreateBookingdefaultJSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *BookingsCreateBookingdefaultJSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin/bookings)
	AdminBookingsListAdminBookings(ctx echo.Context, params AdminBookingsListAdminBookingsParams) error

	// (GET /admin/event-types)
	AdminEventTypesListAdminEventTypes(ctx echo.Context) error

	// (POST /admin/event-types)
	AdminEventTypesCreateEventType(ctx echo.Context) error

	// (DELETE /admin/event-types/{id})
	AdminEventTypesDeleteEventType(ctx echo.Context, id string) error

	// (PUT /admin/event-types/{id})
	AdminEventTypesUpdateEventType(ctx echo.Context, id string) error

	// (POST /bookings)
	BookingsCreateBooking(ctx echo.Context) error

	// (DELETE /bookings/{id})
	BookingsCancelBooking(ctx echo.Context, id string) error

	// (GET /event-types)
	EventTypesListEventTypes(ctx echo.Context) error

	// (GET /slots)
	SlotsListSlots(ctx echo.Context, params SlotsListSlotsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// AdminBookingsListAdminBookings converts echo context to params.
func (w *ServerInterfaceWrapper) AdminBookingsListAdminBookings(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminBookingsListAdminBookingsParams
	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "from", ctx.QueryParams(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "to", ctx.QueryParams(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// ------------- Optional query parameter "eventTypeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "eventTypeId", ctx.QueryParams(), &params.EventTypeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventTypeId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminBookingsListAdminBookings(ctx, params)
	return err
}

// AdminEventTypesListAdminEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) AdminEventTypesListAdminEventTypes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminEventTypesListAdminEventTypes(ctx)
	return err
}

// AdminEventTypesCreateEventType converts echo context to params.
func (w *ServerInterfaceWrapper) AdminEventTypesCreateEventType(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminEventTypesCreateEventType(ctx)
	return err
}

// AdminEventTypesDeleteEventType converts echo context to params.
func (w *ServerInterfaceWrapper) AdminEventTypesDeleteEventType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminEventTypesDeleteEventType(ctx, id)
	return err
}

// AdminEventTypesUpdateEventType converts echo context to params.
func (w *ServerInterfaceWrapper) AdminEventTypesUpdateEventType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminEventTypesUpdateEventType(ctx, id)
	return err
}

// BookingsCreateBooking converts echo context to params.
func (w *ServerInterfaceWrapper) BookingsCreateBooking(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BookingsCreateBooking(ctx)
	return err
}

// BookingsCancelBooking converts echo context to params.
func (w *ServerInterfaceWrapper) BookingsCancelBooking(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BookingsCancelBooking(ctx, id)
	return err
}

// EventTypesListEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) EventTypesListEventTypes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.EventTypesListEventTypes(ctx)
	return err
}

// SlotsListSlots converts echo context to params.
func (w *ServerInterfaceWrapper) SlotsListSlots(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SlotsListSlotsParams
	// ------------- Required query parameter "eventTypeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, true, "eventTypeId", ctx.QueryParams(), &params.EventTypeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter eventTypeId: %s", err))
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "from", ctx.QueryParams(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "to", ctx.QueryParams(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SlotsListSlots(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/admin/bookings", wrapper.AdminBookingsListAdminBookings, options.OperationMiddlewares["AdminBookings_listAdminBookings"]...)
	router.GET(options.BaseURL+"/admin/event-types", wrapper.AdminEventTypesListAdminEventTypes, options.OperationMiddlewares["AdminEventTypes_listAdminEventTypes"]...)
	router.POST(options.BaseURL+"/admin/event-types", wrapper.AdminEventTypesCreateEventType, options.OperationMiddlewares["AdminEventTypes_createEventType"]...)
	router.DELETE(options.BaseURL+"/admin/event-types/:id", wrapper.AdminEventTypesDeleteEventType, options.OperationMiddlewares["AdminEventTypes_deleteEventType"]...)
	router.PUT(options.BaseURL+"/admin/event-types/:id", wrapper.AdminEventTypesUpdateEventType, options.OperationMiddlewares["AdminEventTypes_updateEventType"]...)
	router.POST(options.BaseURL+"/bookings", wrapper.BookingsCreateBooking, options.OperationMiddlewares["Bookings_createBooking"]...)
	router.DELETE(options.BaseURL+"/bookings/:id", wrapper.BookingsCancelBooking, options.OperationMiddlewares["Bookings_cancelBooking"]...)
	router.GET(options.BaseURL+"/event-types", wrapper.EventTypesListEventTypes, options.OperationMiddlewares["EventTypes_listEventTypes"]...)
	router.GET(options.BaseURL+"/slots", wrapper.SlotsListSlots, options.OperationMiddlewares["Slots_listSlots"]...)

}

type AdminBookingsListAdminBookingsRequestObject struct {
	Params AdminBookingsListAdminBookingsParams
}

type AdminBookingsListAdminBookingsResponseObject interface {
	VisitAdminBookingsListAdminBookingsResponse(w http.ResponseWriter) error
}

type AdminBookingsListAdminBookings200JSONResponse []Booking

func (response AdminBookingsListAdminBookings200JSONResponse) VisitAdminBookingsListAdminBookingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminEventTypesListAdminEventTypesRequestObject struct {
}

type AdminEventTypesListAdminEventTypesResponseObject interface {
	VisitAdminEventTypesListAdminEventTypesResponse(w http.ResponseWriter) error
}

type AdminEventTypesListAdminEventTypes200JSONResponse []EventType

func (response AdminEventTypesListAdminEventTypes200JSONResponse) VisitAdminEventTypesListAdminEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminEventTypesCreateEventTypeRequestObject struct {
	Body *AdminEventTypesCreateEventTypeJSONRequestBody
}

type AdminEventTypesCreateEventTypeResponseObject interface {
	VisitAdminEventTypesCreateEventTypeResponse(w http.ResponseWriter) error
}

type AdminEventTypesCreateEventType200JSONResponse EventType

func (response AdminEventTypesCreateEventType200JSONResponse) VisitAdminEventTypesCreateEventTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminEventTypesDeleteEventTypeRequestObject struct {
	Id string `json:"id"`
}

type AdminEventTypesDeleteEventTypeResponseObject interface {
	VisitAdminEventTypesDeleteEventTypeResponse(w http.ResponseWriter) error
}

type AdminEventTypesDeleteEventType204Response struct {
}

func (response AdminEventTypesDeleteEventType204Response) VisitAdminEventTypesDeleteEventTypeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AdminEventTypesDeleteEventTypedefaultJSONResponse struct {
	Body       AdminEventTypesDeleteEventTypedefaultJSONResponseBody
	StatusCode int
}

func (response AdminEventTypesDeleteEventTypedefaultJSONResponse) VisitAdminEventTypesDeleteEventTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body.union); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminEventTypesUpdateEventTypeRequestObject struct {
	Id   string `json:"id"`
	Body *AdminEventTypesUpdateEventTypeJSONRequestBody
}

type AdminEventTypesUpdateEventTypeResponseObject interface {
	VisitAdminEventTypesUpdateEventTypeResponse(w http.ResponseWriter) error
}

type AdminEventTypesUpdateEventType200JSONResponse EventType

func (response AdminEventTypesUpdateEventType200JSONResponse) VisitAdminEventTypesUpdateEventTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminEventTypesUpdateEventTypedefaultJSONResponse struct {
	Body       NotFoundError
	StatusCode int
}

func (response AdminEventTypesUpdateEventTypedefaultJSONResponse) VisitAdminEventTypesUpdateEventTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsCreateBookingRequestObject struct {
	Body *BookingsCreateBookingJSONRequestBody
}

type BookingsCreateBookingResponseObject interface {
	VisitBookingsCreateBookingResponse(w http.ResponseWriter) error
}

type BookingsCreateBooking200JSONResponse Booking

func (response BookingsCreateBooking200JSONResponse) VisitBookingsCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsCreateBookingdefaultJSONResponse struct {
	Body       BookingsCreateBookingdefaultJSONResponseBody
	StatusCode int
}

func (response BookingsCreateBookingdefaultJSONResponse) VisitBookingsCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body.union); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BookingsCancelBookingRequestObject struct {
	Id string `json:"id"`
}

type BookingsCancelBookingResponseObject interface {
	VisitBookingsCancelBookingResponse(w http.ResponseWriter) error
}

type BookingsCancelBooking204Response struct {
}

func (response BookingsCancelBooking204Response) VisitBookingsCancelBookingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type BookingsCancelBookingdefaultJSONResponse struct {
	Body       NotFoundError
	StatusCode int
}

func (response BookingsCancelBookingdefaultJSONResponse) VisitBookingsCancelBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type EventTypesListEventTypesRequestObject struct {
}

type EventTypesListEventTypesResponseObject interface {
	VisitEventTypesListEventTypesResponse(w http.ResponseWriter) error
}

type EventTypesListEventTypes200JSONResponse []EventType

func (response EventTypesListEventTypes200JSONResponse) VisitEventTypesListEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SlotsListSlotsRequestObject struct {
	Params SlotsListSlotsParams
}

type SlotsListSlotsResponseObject interface {
	VisitSlotsListSlotsResponse(w http.ResponseWriter) error
}

type SlotsListSlots200JSONResponse []Slot

func (response SlotsListSlots200JSONResponse) VisitSlotsListSlotsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /admin/bookings)
	AdminBookingsListAdminBookings(ctx context.Context, request AdminBookingsListAdminBookingsRequestObject) (AdminBookingsListAdminBookingsResponseObject, error)

	// (GET /admin/event-types)
	AdminEventTypesListAdminEventTypes(ctx context.Context, request AdminEventTypesListAdminEventTypesRequestObject) (AdminEventTypesListAdminEventTypesResponseObject, error)

	// (POST /admin/event-types)
	AdminEventTypesCreateEventType(ctx context.Context, request AdminEventTypesCreateEventTypeRequestObject) (AdminEventTypesCreateEventTypeResponseObject, error)

	// (DELETE /admin/event-types/{id})
	AdminEventTypesDeleteEventType(ctx context.Context, request AdminEventTypesDeleteEventTypeRequestObject) (AdminEventTypesDeleteEventTypeResponseObject, error)

	// (PUT /admin/event-types/{id})
	AdminEventTypesUpdateEventType(ctx context.Context, request AdminEventTypesUpdateEventTypeRequestObject) (AdminEventTypesUpdateEventTypeResponseObject, error)

	// (POST /bookings)
	BookingsCreateBooking(ctx context.Context, request BookingsCreateBookingRequestObject) (BookingsCreateBookingResponseObject, error)

	// (DELETE /bookings/{id})
	BookingsCancelBooking(ctx context.Context, request BookingsCancelBookingRequestObject) (BookingsCancelBookingResponseObject, error)

	// (GET /event-types)
	EventTypesListEventTypes(ctx context.Context, request EventTypesListEventTypesRequestObject) (EventTypesListEventTypesResponseObject, error)

	// (GET /slots)
	SlotsListSlots(ctx context.Context, request SlotsListSlotsRequestObject) (SlotsListSlotsResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// AdminBookingsListAdminBookings operation middleware
func (sh *strictHandler) AdminBookingsListAdminBookings(ctx echo.Context, params AdminBookingsListAdminBookingsParams) error {
	var request AdminBookingsListAdminBookingsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminBookingsListAdminBookings(ctx.Request().Context(), request.(AdminBookingsListAdminBookingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminBookingsListAdminBookings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminBookingsListAdminBookingsResponseObject); ok {
		return validResponse.VisitAdminBookingsListAdminBookingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminEventTypesListAdminEventTypes operation middleware
func (sh *strictHandler) AdminEventTypesListAdminEventTypes(ctx echo.Context) error {
	var request AdminEventTypesListAdminEventTypesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminEventTypesListAdminEventTypes(ctx.Request().Context(), request.(AdminEventTypesListAdminEventTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminEventTypesListAdminEventTypes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminEventTypesListAdminEventTypesResponseObject); ok {
		return validResponse.VisitAdminEventTypesListAdminEventTypesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminEventTypesCreateEventType operation middleware
func (sh *strictHandler) AdminEventTypesCreateEventType(ctx echo.Context) error {
	var request AdminEventTypesCreateEventTypeRequestObject

	var body AdminEventTypesCreateEventTypeJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminEventTypesCreateEventType(ctx.Request().Context(), request.(AdminEventTypesCreateEventTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminEventTypesCreateEventType")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminEventTypesCreateEventTypeResponseObject); ok {
		return validResponse.VisitAdminEventTypesCreateEventTypeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminEventTypesDeleteEventType operation middleware
func (sh *strictHandler) AdminEventTypesDeleteEventType(ctx echo.Context, id string) error {
	var request AdminEventTypesDeleteEventTypeRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminEventTypesDeleteEventType(ctx.Request().Context(), request.(AdminEventTypesDeleteEventTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminEventTypesDeleteEventType")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminEventTypesDeleteEventTypeResponseObject); ok {
		return validResponse.VisitAdminEventTypesDeleteEventTypeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminEventTypesUpdateEventType operation middleware
func (sh *strictHandler) AdminEventTypesUpdateEventType(ctx echo.Context, id string) error {
	var request AdminEventTypesUpdateEventTypeRequestObject

	request.Id = id

	var body AdminEventTypesUpdateEventTypeJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminEventTypesUpdateEventType(ctx.Request().Context(), request.(AdminEventTypesUpdateEventTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminEventTypesUpdateEventType")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminEventTypesUpdateEventTypeResponseObject); ok {
		return validResponse.VisitAdminEventTypesUpdateEventTypeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BookingsCreateBooking operation middleware
func (sh *strictHandler) BookingsCreateBooking(ctx echo.Context) error {
	var request BookingsCreateBookingRequestObject

	var body BookingsCreateBookingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.BookingsCreateBooking(ctx.Request().Context(), request.(BookingsCreateBookingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BookingsCreateBooking")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(BookingsCreateBookingResponseObject); ok {
		return validResponse.VisitBookingsCreateBookingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BookingsCancelBooking operation middleware
func (sh *strictHandler) BookingsCancelBooking(ctx echo.Context, id string) error {
	var request BookingsCancelBookingRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.BookingsCancelBooking(ctx.Request().Context(), request.(BookingsCancelBookingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BookingsCancelBooking")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(BookingsCancelBookingResponseObject); ok {
		return validResponse.VisitBookingsCancelBookingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// EventTypesListEventTypes operation middleware
func (sh *strictHandler) EventTypesListEventTypes(ctx echo.Context) error {
	var request EventTypesListEventTypesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.EventTypesListEventTypes(ctx.Request().Context(), request.(EventTypesListEventTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EventTypesListEventTypes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(EventTypesListEventTypesResponseObject); ok {
		return validResponse.VisitEventTypesListEventTypesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SlotsListSlots operation middleware
func (sh *strictHandler) SlotsListSlots(ctx echo.Context, params SlotsListSlotsParams) error {
	var request SlotsListSlotsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SlotsListSlots(ctx.Request().Context(), request.(SlotsListSlotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SlotsListSlots")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SlotsListSlotsResponseObject); ok {
		return validResponse.VisitSlotsListSlotsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
